### ISSUE TITLE
Error with jQuery 4.0.0

### ISSUE THREAD

**Issue by olape-git** [cmb69/foldergallery_xh#60]
```
Uncaught TypeError: t.isFunction is not a function
    Y jQuery
    <anonymous> https://....
    jQuery 13
index.php:6:7964
```
Under jQuery 4.0.0, it only works with jQuery Migrate 4.0.2.
